services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - ./eventstore-data:/var/lib/eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password